apiVersion: apps/v1
kind: Deployment
metadata:
    name: rythm-app1
    labels:
        app: app1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app1
    template:
        metadata:
            labels:
                app: app1
        spec:
            containers:              
            - env:
              image: docker.io/brandonrvice/rythm-app1:latest
              imagePullPolicy: Always
              name: rythm-app1
              ports:
              - containerPort: 80
